export const LIGHT_SELECTED = 'LIGHT_SELECTED';
export const LIGHT_VALUE = 'LIGHT_VALUE';

export const IDLE_VALUE = 'IDLE_VALUE';

export const SPEED_SELECTED = 'SPEED_SELECTED';

export const PROFILE_DBDATA = 'PROFILE_DBDATA';
export const LIGHT_DBDATA = 'LIGHT_DBDATA';
export const VOLTAGE_DBDATA = 'VOLTAGE_DBDATA';